### PR TITLE
Parse queryEnd for boost + minimum match

### LINKED ISSUE #113: Fix parsing trailing characters as another term
```scala
  test("parse boost does not parse with trailing 'f' on boost".fail) {
    // TODO the trailing `f` is parsing as another term and it should not
    val r = parseQ("fieldName42:cat42^3.1f")
    assert(r.isLeft)
  }
```

Encountered in https://github.com/cozydev-pink/lucille/pull/112

### PR DESCRIPTION
**Pull request by samspills**
Resolves #113 

- switches our `spaces` parser to use `wsp`, it's the exact same definition
- add a `queryEnd` definition; queries can end with whitespace, the end of the string, or the end of a group (`)`)
- ensure we hit a `queryEnd` in our boost and minimum match queries

### CODE REVIEW

File: core/src/main/scala/pink/cozydev/lucille/QueryParser.scala [hunk 1]
```diff
@@ -153,14 +155,16 @@ private object Parser {
...
+      Boost(qf._1, qf._2)
+    )
   }
 
   /**  Parse a minimum match query
     * e.g. '(one two three)@2'
     */
   def minimumMatchQ(query: P[Query]): P[MinimumMatch] = {
-    val matchNum = P.char('@') *> int
+    val matchNum = P.char('@') *> int <* queryEnd
```
Comment (valencik) [inline core/src/main/scala/pink/cozydev/lucille/QueryParser.scala:167]: This is actually more readable too, I really like this change!

File: core/src/test/scala/pink/cozydev/lucille/ParserSuite.scala [hunk 2]
```diff
@@ -127,13 +127,13 @@ class SingleSimpleQuerySuite extends munit.FunSuite {
     assertSingleTerm(r, Field("fieldName42", Boost(Group(And(Term("cats"), Term("dogs"))), 20f)))
   }
 
-  test("parse boost does not parse with trailing 'f' on boost".fail) {
+  test("parse boost does not parse with trailing 'f' on boost") {
```
Comment (valencik) [inline core/src/test/scala/pink/cozydev/lucille/ParserSuite.scala:130]: 🎉

**Review by valencik — APPROVED** [review]
Thanks so much, this is awesome!

File: core/src/main/scala/pink/cozydev/lucille/QueryParser.scala [hunk 3]
```diff
@@ -66,6 +66,8 @@ private object Parser {
     P.charIn(baseRange -- special)
   val reserved = Set("OR", "||", "AND", "&&", "NOT", "+", "-", "/")
 
+  val queryEnd = (wsp | P.end | P.char(')')).peek
```
Comment (kejifasuyi) [inline core/src/main/scala/pink/cozydev/lucille/QueryParser.scala:69]: Curious - What is peek doing really?

File: core/src/test/scala/pink/cozydev/lucille/ParserSuite.scala [hunk 4]
```diff
@@ -127,13 +132,13 @@ class SingleSimpleQuerySuite extends munit.FunSuite {
...
     // TODO the trailing `f` is parsing as another term and it should not
```
Comment (kejifasuyi) [inline core/src/test/scala/pink/cozydev/lucille/ParserSuite.scala:136]: Do we want to ditch this comment?

**Review by kejifasuyi — APPROVED** [review]
Looks good to me, just a tiny question. Thanks Sam! 🎉

File: core/src/main/scala/pink/cozydev/lucille/QueryParser.scala (hunk 3 above)
Comment (samspills) [reply core/src/main/scala/pink/cozydev/lucille/QueryParser.scala:69]: `peek` succeeds if the underlying parser would succeed but then it always backtracks afterwards, so you're "peeking" at the result but not consuming it. In our case what it means is that we're making sure a boost or a minimum match query ends with one of the those three characters, but we don't consume those characters as part of the query. This is mostly important for `)`, because the closing paren is actually part of the `group` query and if we consume it then we wouldn't be able to properly parse the group (in my head, I think of it like boost/minimum match need to know it's there, but the `)` doesn't belong to them)

Does that make sense?

File: core/src/test/scala/pink/cozydev/lucille/ParserSuite.scala (hunk 4 above)
Comment (samspills) [reply core/src/test/scala/pink/cozydev/lucille/ParserSuite.scala:136]: Ah yes! 

Making a suggestion b/c I'm lazy 😅 
```suggestion
```

File: core/src/main/scala/pink/cozydev/lucille/QueryParser.scala (hunk 3 above)
Comment (kejifasuyi) [reply core/src/main/scala/pink/cozydev/lucille/QueryParser.scala:69]: It does. Look at us - you explaining stuff to me on PRs. I've missed this! 
Thanks

Comment (samspills) [reply core/src/main/scala/pink/cozydev/lucille/QueryParser.scala:69]: Me tooooooo ❤️❤️❤️❤️❤️❤️❤️
